export const ImageData = Object.freeze([
  {
    original: require("assets/images/commercial/commercial-1.1_4x3.png"),
    thumbnail: require("assets/images/commercial/commercial-1.1_4x3.png"),
    title: "commercial-1.1_4x3",
    alt: "commercial-1.1_4x3",
  },
  {
    original: require("assets/images/commercial/commercial-2.1_16x9.png"),
    thumbnail: require("assets/images/commercial/commercial-2.1_16x9.png"),
    title: "commercial-2.1_16x9",
    alt: "commercial-2.1_16x9",
  },
  {
    original: require("assets/images/commercial/commercial-2.2_16x9.png"),
    thumbnail: require("assets/images/commercial/commercial-2.2_16x9.png"),
    title: "commercial-2.2_16x9",
    alt: "commercial-2.2_16x9",
  },
  {
    original: require("assets/images/residential/residential-1.1_9x16.png"),
    thumbnail: require("assets/images/residential/residential-1.1_9x16.png"),
    title: "residential-1.1_9x16",
    alt: "residential-1.1_9x16",
  },
  {
    original: require("assets/images/residential/residential-2.1_1x1.png"),
    thumbnail: require("assets/images/residential/residential-2.1_1x1.png"),
    title: "residential-2.1_1x1",
    alt: "residential-2.1_1x1",
  },
  {
    original: require("assets/images/commercial/commercial-2.3_1x1.png"),
    thumbnail: require("assets/images/commercial/commercial-2.3_1x1.png"),
    title: "commercial-2.3_1x1",
    alt: "commercial-2.3_1x1",
  },
  {
    original: require("assets/images/commercial/commercial-2.5_3x4.png"),
    thumbnail: require("assets/images/commercial/commercial-2.5_3x4.png"),
    title: "commercial-2.5_3x4",
    alt: "commercial-2.5_3x4",
  },
  {
    original: require("assets/images/commercial/commercial-3.1_4x3.png"),
    thumbnail: require("assets/images/commercial/commercial-3.1_4x3.png"),
    title: "commercial-3.1_4x3",
    alt: "commercial-3.1_4x3",
  },
  {
    original: require("assets/images/commercial/commercial-4.1_1x1.png"),
    thumbnail: require("assets/images/commercial/commercial-4.1_1x1.png"),
    title: "commercial-4.1_1x1",
    alt: "commercial-4.1_1x1",
  },
  {
    original: require("assets/images/commercial/commercial-4.3_1x1.png"),
    thumbnail: require("assets/images/commercial/commercial-4.3_1x1.png"),
    title: "commercial-4.3_1x1",
    alt: "commercial-4.3_1x1",
  },
  {
    original: require("assets/images/commercial/commercial-5.1_16x9.png"),
    thumbnail: require("assets/images/commercial/commercial-5.1_16x9.png"),
    title: "commercial-5.1_16x9",
    alt: "commercial-5.1_16x9",
  },
  {
    original: require("assets/images/commercial/commercial-6.1_4x3.png"),
    thumbnail: require("assets/images/commercial/commercial-6.1_4x3.png"),
    title: "commercial-6.1_4x3",
    alt: "commercial-6.1_4x3",
  },
  {
    original: require("assets/images/commercial/commercial-6.2_4x3.png"),
    thumbnail: require("assets/images/commercial/commercial-6.2_4x3.png"),
    title: "commercial-6.2_4x3",
    alt: "commercial-6.2_4x3",
  },
  {
    original: require("assets/images/commercial/commercial-6.3_4x3.png"),
    thumbnail: require("assets/images/commercial/commercial-6.3_4x3.png"),
    title: "commercial-6.3_4x3",
    alt: "commercial-6.3_4x3",
  },
  {
    original: require("assets/images/commercial/commercial-7.1_16x9.png"),
    thumbnail: require("assets/images/commercial/commercial-7.1_16x9.png"),
    title: "commercial-7.1_16x9",
    alt: "commercial-7.1_16x9",
  },
  {
    original: require("assets/images/commercial/commercial-7.2_16x9.png"),
    thumbnail: require("assets/images/commercial/commercial-7.2_16x9.png"),
    title: "commercial-7.2_16x9",
    alt: "commercial-7.2_16x9",
  },
  {
    original: require("assets/images/commercial/commercial-7.3_16x9.png"),
    thumbnail: require("assets/images/commercial/commercial-7.3_16x9.png"),
    title: "commercial-7.3_16x9",
    alt: "commercial-7.3_16x9",
  },
  {
    original: require("assets/images/commercial/commercial-8.1_1x1.png"),
    thumbnail: require("assets/images/commercial/commercial-8.1_1x1.png"),
    title: "commercial-8.1_1x1",
    alt: "commercial-8.1_1x1",
  },
]);
